### ISSUE TITLE
Octal numbers in ES5

### ISSUE THREAD

**Issue by sateffen** [rse/es6-features#1]
Heyho, I just wanted to add a little thing:

http://es6-features.org/#BinaryOctalLiteral doesn't tell the simplest way of handling octal numbers. To write octal numbers your number simply has to start with a leading zero, so

```
0767 === 503 -> true
010 === parseInt('10', 8) -> true (result: 8)
077 === parseInt('77', 8) -> true (result: 63)
```

You could add this to the page, because it is an existing feature in ES5, even though a lot of people don't know about.

**Comment by rse** [comment]
Yes, but those were removed in ES3 for strict mode and work just on non-strict and/or backward compat mode in ES5/ES6. Nevertheless, I've added "|0767| === 503; // only in non-strict, backward compatibility mode" now to the ES5 snippet. Thanks for the hint.
