### ISSUE TITLE
confusing variable names

### ISSUE THREAD

**Issue by thujone** [rse/es6-features#102]
Hi, just a general comment. Sometimes I find the variable names used in examples completely confounding. For example, sometimes the variable name is ''dst". Sometimes it's "quud". In the latter, I guess it's supposed to signify a random variable name. In the case of the former, I'm not sure if it stands for something I can't think of. I think the code examples would be better if the variable names were more descriptive / longer.

**Comment by rse** [comment]
"dst" is "destination" and 3 chars long to match "src" (source). But, yes, it might be too cryptic. I've now at least changed it to "dest". The "quud" you mentioned is "quux" and will not be changed, as it is a fixed-term "meta-syntactic variable" (check out e.g. https://en.wikipedia.org/wiki/Metasyntactic_variable)
