### ISSUE TITLE
support status

### ISSUE THREAD

**Issue by techfort** [rse/es6-features#12]
Hey Ralf, great work on es6-features.org
Would be nice to have each feature classified with their support status, and also I couldn't find list comprehensions, are they there and I can't find them or is it missing?
Keep it up!

**Comment by rse** [comment]
What exactly do you mean by "support status"? The support in browsers and other runtimes is completely different for each one. In the FAQ there is a link to the kangax table http://kangax.github.io/compat-table/es6/. This is more info than what I could provide, I think. And most important: Babel allows you to already use all those features...

The list comprehensions were not taken over into the ES6 standard according to the latest drafts. They might occur in ES7, but definitely not in ES6. Sorry.

**Comment by techfort** [comment]
Hey Ralph, I suppose my question is similar to #2  in that it also extends to node.js and io.js (e.g. what flag to use to enable the feature). As es6-features.org is such a great reference it would be great if browser/node support was readily available instead of having to refer to a second source. But sure, that's up to you.

**Comment by rse** [comment]
Node.js/IO.js support is available, of course. Just use the Babel require hook http://babeljs.io/docs/usage/require/ in Node.js and IO.js or use "iojs --harmony" in IO.js for a reduced ES6-support. The "node --harmony" you can forget, it uses a too old V8 engine...

**Comment by rse** [comment]
See https://github.com/rse/es6-support, a new project from me where I assemble code examples which show how to use ECMAScript 6 in various scenarios.

**Comment by techfort** [comment]
Thanks!
