### ISSUE TITLE
Block-Scoped Functions code is wrong.

### ISSUE THREAD

**Issue by webbedspace** [rse/es6-features#16]
[This](https://github.com/rse/es6-features/blob/gh-pages/features.txt#L69-L79) is wrong. That code depicts function-scoped functions. It should actually be this:

```
{
    function foo() {...}
    foo();
    {
        function bar() {...}
        bar();
    }
}
```

ES5:

```
function foo() {...}
function bar() {...}
{
    foo();
    {
        bar();
    }
}
```

**Comment by rse** [comment]
Good catch. Thanks for the hint. I've revised the stuff and now showcase both Function-Scoped Functions and Block-Scoped Functions. How it is correct now.
