### ISSUE TITLE
Function-Scoped Functions aren't an ES6 feature

### ISSUE THREAD

**Issue by webbedspace** [rse/es6-features#18]
Placing a function declaration inside another function declaration has been valid JavaScript since Netscape 2.0, and moreover has never been disallowed by strict mode.

**Comment by rse** [comment]
Yes, but not in strict mode since ES5. That's the point here. But I've made it more explicit now. Thanks for the feedback.

**Comment by webbedspace** [comment]
I just said:

> it has never been disallowed by strict mode.

The only thing strict mode disallowed was block-scoped function declarations. _Not_ function-scoped function declarations.

To summarise:
ALLOWED IN ES5:

```
"use strict"; function A() { function B() {} }
```

NOT ALLOWED IN ES5:

```
"use strict"; { function B() {} }
```

**Comment by rse** [comment]
Ah, understood. You're right, I was wrong here. Now fixed. Thanks for clarification.
