### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by lukasolson** [rse/es6-features#2]
First of all, this is an incredible tool and I'm really excited about it.

I'd love if there were some browser compatibility table, similar to [what MDN provides](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Browser_compatibility). Is this feasible?

Thanks!

**Comment by rse** [comment]
I've added a link to kangax compat table to the FAQ (see README.md) which always provides the latest support status quo.
