### ISSUE TITLE
`Proxy` bug

### ISSUE THREAD

**Issue by zloirock** [rse/es6-features#20]
http://es6-features.org/#Proxing
~~`proxy.foo   === "Hello, foo"`~~
`proxy.foo   === "Hello, foo!!"`

**Comment by rse** [comment]
No, I think it was correct as the original method is used for "foo". I made it more explicit by using a more different result.

**Comment by zloirock** [comment]
It's not correct example. Try in FF. Possible fix:

``` js
return name in receiver ? receiver[name] : `Hello, ${name}`;
```

**Comment by rse** [comment]
Ah, good catch. Thanks. Now fixed the way you suggested.
