### ISSUE TITLE
Modernized vs. Traditional mismatch

### ISSUE THREAD

**Issue by orand** [rse/es6-features#3]
Currently the examples default to ES6 using the Modernized style (no semicolons) and ES5 using the Traditional style (with semicolons).  This introduces a misleading and orthogonal extra diff when comparing the various examples.  Please consider making Modernized/Traditional a single setting that modifies both the ES6 and ES5 example code at the same time.  And please consider defaulting it to traditional.  As it stands, I hesitate to forward a link to this site to my coworkers who are just getting started with ES6 since it adds unnecessary confusion and will trigger a knee-jerk reaction against ES6 due to "ES6 is anti-semicolons!" :wink:

**Comment by rse** [comment]
Actually, I have to confess that I fully intentionally use this asymmetry in the defaults as most people with ES5 background use the traditional semicolon style while for ES6 this extra and not necessary syntactic sugar IMHO should be absolutely avoided. Yes, I know, that's a fully subjective opinion, course. But I've even added an extra FAQ entry just for this already from the beginning and I do not plan to change this as I do not want to promote the useless semicolon style any longer with ES6 -- at least not from my side ;-)

**Comment by rse** [comment]
For you convenience you can now send your co-workers the URL "http://es6-features.org/#traditional" which enforces the traditional style on both ES5 and ES6 code snippets. But better would be if you send your co-workers the URL "http://es6-features.org/#modernized" and tell them to get rid of the useless syntactic sugar they are got used to.

**Comment by orand** [comment]
Thanks!  Your points are understood, and your concessions are much appreciated.  You know what it takes to boil a frog... don't shock their system too much all at once or they'll jump out...

As to the "absolute" uselessness of semicolons, just today I found the following syntax style in a coworker's ES6 code, which is still a problem even in ES6 (ignore his trailing semicolon :wink:)

```
return someExpression
    ? something
    : yet.another.thing;
```
