### ISSUE TITLE
Mention of Babel (the transpiler)?

### ISSUE THREAD

**Issue by dead-claudia** [rse/es6-features#32]
It is an ES6 to ES5 transpiler that, with its polyfill, is nearly spec compliant.

The biggest area where it deviates from spec is its [handling of the temporal dead zone (TDZ)](https://github.com/babel/babel/issues/563) ([Traceur has the same problem](https://github.com/google/traceur-compiler/issues/1382)). It's hard for a transpiler to know if a function call is reading an undeclared variable or unallocated `this` or not, and the necessary safety wrapper is an insane performance drop.

Other than that, it's become the de facto standard.

**Comment by rse** [comment]
es6-features.org twice (see right bottom corner) links to https://github.com/rse/es6-support and there all examples are Babel based. Additionally, Babel is mentioned as the solution in question "*How can I use ECMAScript 6 if my JavaScript runtime still does not support it?" in the README of es6-features project on Github. I think this should be sufficient, isn't it?

**Comment by dead-claudia** [comment]
Didn't notice that part. Oops.
