### ISSUE TITLE
ECMAScript 5 code for Template Strings Custom Interpolation is not correct

### ISSUE THREAD

**Issue by peabnuts123** [rse/es6-features#36]
In the section "Custom Interpolation" under "Template Strings" the following code is presented as a backwards compatible ECMAScript 5 equivalent: 

```
ES6: get`http://example.com/foo?bar=${bar + baz}&quux=${quux}`
ES5: get([ "http://example.com/foo?bar=", "&quux=", "" ], [ bar + baz, quux ]);
```

This is incorrect as per the Tagged template strings specification for ES6. The templated variables (quux, bar+baz) are passed into the template function as separate function arguments, not as an array ([see mozilla dev reference](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings#Tagged_template_strings)).

The actual code should read something like:

```
ES6: get`http://example.com/foo?bar=${bar + baz}&quux=${quux}`
ES5: get([ "http://example.com/foo?bar=", "&quux=", "" ], bar+baz, quux);
```

This array-like behaviour is, however, often implemented within the ES6 context using [rest parameters](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/rest_parameters), as this behaviour is arguably more practical to use.

**Comment by rse** [comment]
Good catch! Thanks for the hint. Now fixed.
