### ISSUE TITLE
Line height of marks of syntax highlight should be increased

### ISSUE THREAD

**Issue by 599316527** [rse/es6-features#60]
![ecmascript_6__new_features__overview_and_comparison](https://cloud.githubusercontent.com/assets/1331413/14006889/b147e604-f1ac-11e5-8934-c275bcecc8df.jpg)

Half bottom of g, j, p, q, y don't displayed properly.

**Comment by e-cloud** [comment]
agree +1

**Comment by corvae** [comment]
Also brackets:
![capture1](https://cloud.githubusercontent.com/assets/7141060/18019107/3b82db22-6ba0-11e6-8b76-d7de1dddb20e.PNG)
