### ISSUE TITLE
Missing semicolons

### ISSUE THREAD

**Issue by and3k5** [rse/es6-features#61]
It seems like semicolons doesn't appear on ES6 examples on the pages.
If you look at [features.txt:605](https://github.com/rse/es6-features/blob/gh-pages/features.txt#L605) you see semicolons even though they're not visible [on the site](http://es6-features.org/#ClassDefinition).

**Comment by rse** [comment]
They can be enabled/disabled on the website by clicking on "syntactic sugar: reduced | traditional". The semicolons are intentionally disabled for ES6 code. For more details check out question "Why does the website default use the "reduced" syntactic sugar style (without semicolons) for ECMAScript 6 and the "traditional" syntactic sugar style (with semicolons) for ECMAScript 5?" on the FAQ under https://github.com/rse/es6-features/blob/gh-pages/README.md

**Comment by and3k5** [comment]
Ah I see. I was going right into reporting this, since I just thought it was a mistake. 

I might need to read more about ES6. Thanks! :-)
