### ISSUE TITLE
Meta-Programming Proxing trap function as property 'get'?

### ISSUE THREAD

**Issue by eloone** [rse/es6-features#7]
In http://es6-features.org/#Proxing:

Instead of:

```
let proxy = new Proxy(target, {
    get (receiver, name) {
        return `Hello, ${name}!!`
    }
})
```

Shouldn't it be:

```
let proxy = new Proxy(target, {
    get: function (receiver, name) {
        return `Hello, ${name}!!`
    }
})
```

?

**Comment by rse** [comment]
No, ES6 supports method notation directly within object literals, so the syntax actually is correct. But this brings me to the point that we should perhaps showcase this feature separately and not implicitly within the proxy snippet...

**Comment by rse** [comment]
Now showcased under http://es6-features.org/#MethodProperties

**Comment by eloone** [comment]
Ok that's very interesting to know. The new section is very helpful thanks!
