### ISSUE TITLE
Should have mutable and non mutable collection types

### ISSUE THREAD

**Issue by KamalHunzai** [rse/es6-features#72]
ES6 minor releases should include having options between mutable and non mutable collection. It can be useful for developing progressive web apps and mobile apps.

**Comment by rse** [comment]
Yes, immutable collections can be useful for ECMAScript. But you have to propose this to the ECMAScript standardization group. This es6-features project just shows the features of ECMAScript 6, nothing more, nothing less. We do not standardize ECMAScript. We are unrelated to the standardization group.
