### ISSUE TITLE
Modernized style

### ISSUE THREAD

**Issue by mondalaci** [rse/es6-features#8]
I see that in the source code viewers there's a modernized vs traditional mode, the modernized not containing any semicolons. What makes this any modern than the semicoloned version? I personally think it's a bad practice. Worse yet, the modernized is the default for ES6, suggesting that no semicolons should be used for ES6 code.

**Comment by rse** [comment]
My answer is already in the FAQ in README.md. Please see there.

**Comment by mondalaci** [comment]
@rse Thanks for the quick reply, I really should have RTFMed.

I still think the traditional / modernized naming is a higly misleading and arbitrary one. It suggests that ES6 somehow promotes not using semicolons. Also, I think there's nothing "modern" about omitting semicolons. Regardless, you've definitely made your point in the docs but I think these terms are making the otherwise super-polished site somewhat confusing.

Another issue: your term of the "automatic semicolon interference" is not used by anyone else. "Automatic semicolon _insertion_" is the correct term that is used.

Thanks for this site and keep it up!

**Comment by rse** [comment]
The perhaps too offending "modernized" is now named "reduced" on the website and I've replaced the incorrect word "interference" with "inference/insertion" in the FAQ. Thanks for the hints.

**Comment by mondalaci** [comment]
Thanks for the quick fix, great job!
