### ISSUE TITLE
Map/Set & WeakMap/WeakSet - Uncaught ReferenceError: s is not defined

### ISSUE THREAD

**Issue by damiangreen** [rse/es6-features#81]
The Map/Set example doesn't work

[https://github.com/rse/es6-features/blob/38f6a8499116f5207806272eaa6a4a9153293068/features.txt](https://github.com/rse/es6-features/blob/38f6a8499116f5207806272eaa6a4a9153293068/features.txt)

```
let m = new Map()
m.set("hello", 42)
m.set(s, 34)
```

**Comment by andrit** [comment]
I saw that too.

Should be:

`let m = new Map, s;
m.set("hello", 42);
m.set(s, 34);
m.get(s) === 34;
m.size === 2;
for (let [ key, val ] of m.entries())
    console.log(key + " = " + val);
`

**Comment by damiangreen** [comment]
I created a pull request a while back. No maintainers around it appears though
