### ISSUE TITLE
Unexpected number of arguments

### ISSUE THREAD

**Issue by dsbonev** [rse/es6-features#9]
In this [example](https://github.com/rse/es6-features/blob/042137bc30c883c39bb4855635e5d0ff1550bc9f/features.txt#L410) two arguments are provided where one is expected. This hinders code comprehension as in the ES6 style the function is not named explicitly, I had to look at the ES5 style to understand that the default exported function is the one imported as `exp`.

**Comment by rse** [comment]
Now fixed. Thanks for the hint.
